// <auto-generated />
using System;
using MetroLayag.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetroLayag.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250616180636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetroLayag.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasDisembarked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<string>("StartingStation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("MetroLayag.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "MainAdmin",
                            Station = "Main Office",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "Escolta",
                            Username = "escolta"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "Lawton",
                            Username = "lawton"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "Quinta",
                            Username = "quinta"
                        },
                        new
                        {
                            Id = 5,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "PUP",
                            Username = "pup"
                        },
                        new
                        {
                            Id = 6,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "Sta. Ana",
                            Username = "staana"
                        },
                        new
                        {
                            Id = 7,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "Lambingan",
                            Username = "lambingan"
                        },
                        new
                        {
                            Id = 8,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "Valenzuela",
                            Username = "valenzuela"
                        },
                        new
                        {
                            Id = 9,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "Hulo",
                            Username = "hulo"
                        },
                        new
                        {
                            Id = 10,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "Guadalupe",
                            Username = "guadalupe"
                        },
                        new
                        {
                            Id = 11,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "Maybunga",
                            Username = "maybunga"
                        },
                        new
                        {
                            Id = 12,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "San Joaquin",
                            Username = "sanjoaquin"
                        },
                        new
                        {
                            Id = 13,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "Kalawaan",
                            Username = "kalawaan"
                        },
                        new
                        {
                            Id = 14,
                            PasswordHash = "$2a$11$fJ8yUYDZQsMZVc/j8JNV.e7ijmTc0S3IAYtbnmvfRMyEvN6VvFHBu",
                            Role = "StationAdmin",
                            Station = "Pinagbuhatan",
                            Username = "pinagbuhatan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
